/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VIEW;

import DAO.DoramaDAO;
import DTO.DoramaDTO;
import DTO.Sessao;
import javax.swing.JOptionPane;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Pichau
 */
public class telaLista extends javax.swing.JFrame {

    /**
     * Creates new form telaLista
     */
    public telaLista() {
        initComponents();
        setLocationRelativeTo(null);
        listarDoramas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addDorama = new javax.swing.JButton();
        voltar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaDorama = new javax.swing.JTable();
        lista = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        addDorama.setBackground(new java.awt.Color(252, 18, 76));
        addDorama.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        addDorama.setForeground(new java.awt.Color(255, 255, 255));
        addDorama.setText("ADICIONAR NOVO DORAMA");
        addDorama.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        addDorama.setMaximumSize(new java.awt.Dimension(71, 22));
        addDorama.setMinimumSize(new java.awt.Dimension(71, 22));
        addDorama.setPreferredSize(new java.awt.Dimension(71, 22));
        addDorama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDoramaActionPerformed(evt);
            }
        });
        getContentPane().add(addDorama);
        addDorama.setBounds(110, 810, 210, 30);

        voltar.setBackground(new java.awt.Color(252, 18, 76));
        voltar.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        voltar.setForeground(new java.awt.Color(255, 255, 255));
        voltar.setText("VOLTAR");
        voltar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        voltar.setMaximumSize(new java.awt.Dimension(71, 22));
        voltar.setMinimumSize(new java.awt.Dimension(71, 22));
        voltar.setPreferredSize(new java.awt.Dimension(71, 22));
        voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarActionPerformed(evt);
            }
        });
        getContentPane().add(voltar);
        voltar.setBounds(170, 860, 90, 30);

        jScrollPane1.setBackground(new java.awt.Color(252, 18, 76));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane1.setForeground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setToolTipText("");
        jScrollPane1.setViewportBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        tabelaDorama.setBackground(new java.awt.Color(252, 149, 165));
        tabelaDorama.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        tabelaDorama.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Plataforma", "Nome", "Gênero", "Temporada", "Episódio", "Observação"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaDorama.setToolTipText("");
        tabelaDorama.setFocusable(false);
        tabelaDorama.setGridColor(new java.awt.Color(255, 255, 255));
        tabelaDorama.setOpaque(false);
        tabelaDorama.setPreferredSize(new java.awt.Dimension(430, 80));
        tabelaDorama.setRequestFocusEnabled(false);
        tabelaDorama.setSelectionBackground(new java.awt.Color(0, 0, 0));
        tabelaDorama.setSelectionForeground(new java.awt.Color(255, 255, 255));
        tabelaDorama.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tabelaDorama);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 280, 430, 510);

        lista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/image/dra. doramas app/6.png"))); // NOI18N
        getContentPane().add(lista);
        lista.setBounds(0, 0, 430, 932);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarActionPerformed
         telaAbertura objTelaAbertura = new telaAbertura();
            objTelaAbertura.setVisible(true);
            dispose();
    }//GEN-LAST:event_voltarActionPerformed

    private void addDoramaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDoramaActionPerformed
       telaAdicionarDorama objTelaAdicionarDorama = new telaAdicionarDorama();
            objTelaAdicionarDorama.setVisible(true);
            dispose();
    }//GEN-LAST:event_addDoramaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaLista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaLista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaLista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaLista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaLista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addDorama;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lista;
    private javax.swing.JTable tabelaDorama;
    private javax.swing.JButton voltar;
    // End of variables declaration//GEN-END:variables

    private void listarDoramas() {

        try {
            DoramaDAO objdoramadao = new DoramaDAO();

            DefaultTableModel model = (DefaultTableModel) tabelaDorama.getModel();
            model.setNumRows(0);
            
            String Usuario_email = Sessao.getUsuario_email();
                      
                  ArrayList<DoramaDTO> lista = objdoramadao.pesquisarDorama(Usuario_email);

            for (int num = 0; num < lista.size(); num++) {
                model.addRow(new Object[]{
                    lista.get(num).getPlataforma(),
                    lista.get(num).getNome(),
                    lista.get(num).getGenero(),
                    lista.get(num).getTemp(),
                    lista.get(num).getEps(),
                    lista.get(num).getObservacao()
                });
            }

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "listar Doramas VIEW: " + erro);
        }

    }

}
