package VIEW;

import DAO.UsuarioDAO;
import DTO.Sessao;
import DTO.UsuarioDTO;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

public class telaLogin1 extends javax.swing.JFrame {

    /**
     * Creates new form telaLogin1
     */
    public telaLogin1() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtsenha = new javax.swing.JTextField();
        txtemail = new javax.swing.JTextField();
        btnentrar = new javax.swing.JButton();
        login = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        txtsenha.setFont(new java.awt.Font("Microsoft YaHei", 0, 12)); // NOI18N
        txtsenha.setBorder(null);
        txtsenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsenhaActionPerformed(evt);
            }
        });
        getContentPane().add(txtsenha);
        txtsenha.setBounds(40, 790, 350, 20);

        txtemail.setFont(new java.awt.Font("Microsoft YaHei", 0, 12)); // NOI18N
        txtemail.setBorder(null);
        txtemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtemailActionPerformed(evt);
            }
        });
        getContentPane().add(txtemail);
        txtemail.setBounds(40, 670, 350, 30);

        btnentrar.setBackground(new java.awt.Color(252, 18, 76));
        btnentrar.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        btnentrar.setForeground(new java.awt.Color(255, 255, 255));
        btnentrar.setText("ENTRAR");
        btnentrar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnentrar.setMaximumSize(new java.awt.Dimension(71, 22));
        btnentrar.setMinimumSize(new java.awt.Dimension(71, 22));
        btnentrar.setPreferredSize(new java.awt.Dimension(71, 22));
        btnentrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnentrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnentrar);
        btnentrar.setBounds(180, 850, 71, 22);

        login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/image/dra. doramas app/3.png"))); // NOI18N
        getContentPane().add(login);
        login.setBounds(0, 0, 430, 932);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtsenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsenhaActionPerformed

    private void txtemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtemailActionPerformed

    private void btnentrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnentrarActionPerformed
         try {
            String email, senha; 
            
            email = txtemail.getText();
            senha = txtsenha.getText();  
            
            UsuarioDTO objusuariodto = new UsuarioDTO();
            objusuariodto.setemail(email);
            objusuariodto.setsenha(senha);
           
            UsuarioDAO objusariodao = new UsuarioDAO();
            ResultSet rsusariodao = objusariodao.autenticacaoUsuario(objusuariodto);
            
            if(rsusariodao.next()){
                Sessao.setUsuario_email(email); 
                System.out.println("Email armazenado na sessão: " + email);

                telaAbertura objTelaAbertura = new telaAbertura();
                objTelaAbertura.setVisible(true);
                dispose();
                
            }else{
                JOptionPane.showMessageDialog(null,"Usuário ou Senha Inválida!");
            }
            } catch (SQLException erro) {
               JOptionPane.showMessageDialog(null, "Login" + erro);
            }
        
    }//GEN-LAST:event_btnentrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (ClassNotFoundException ex) {
        java.util.logging.Logger.getLogger(telaLogin1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
        java.util.logging.Logger.getLogger(telaLogin1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
        java.util.logging.Logger.getLogger(telaLogin1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
        java.util.logging.Logger.getLogger(telaLogin1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            new telaLogin1().setVisible(true);
        }
    });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnentrar;
    private javax.swing.JLabel login;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtsenha;
    // End of variables declaration//GEN-END:variables
}
