/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VIEW;

/**
 *
 * @author Pichau
 */
public class telaAbertura extends javax.swing.JFrame {

    /**
     * Creates new form telaAbertura
     */
    public telaAbertura() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSair = new javax.swing.JButton();
        btnadiciona = new javax.swing.JButton();
        btnlista = new javax.swing.JButton();
        ABERTURA = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        btnSair.setBackground(new java.awt.Color(252, 18, 76));
        btnSair.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        btnSair.setForeground(new java.awt.Color(255, 255, 255));
        btnSair.setText("Sair");
        btnSair.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        getContentPane().add(btnSair);
        btnSair.setBounds(0, 410, 90, 60);

        btnadiciona.setBackground(new java.awt.Color(252, 18, 76));
        btnadiciona.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        btnadiciona.setForeground(new java.awt.Color(255, 255, 255));
        btnadiciona.setText("Adicionar Dorama");
        btnadiciona.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnadiciona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnadicionaActionPerformed(evt);
            }
        });
        getContentPane().add(btnadiciona);
        btnadiciona.setBounds(0, 350, 230, 60);

        btnlista.setBackground(new java.awt.Color(252, 18, 76));
        btnlista.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        btnlista.setForeground(new java.awt.Color(255, 255, 255));
        btnlista.setText("Minha Lista");
        btnlista.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnlista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlistaActionPerformed(evt);
            }
        });
        getContentPane().add(btnlista);
        btnlista.setBounds(0, 300, 160, 50);

        ABERTURA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/image/dra. doramas app/dra. doramas app.png"))); // NOI18N
        getContentPane().add(ABERTURA);
        ABERTURA.setBounds(0, 0, 430, 932);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnadicionaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnadicionaActionPerformed
        telaAdicionarDorama objTelaAdicionarDorama = new telaAdicionarDorama();
            objTelaAdicionarDorama.setVisible(true);
            dispose();
    }//GEN-LAST:event_btnadicionaActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnlistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlistaActionPerformed
        telaLista objTelaLista = new telaLista();
            objTelaLista.setVisible(true);
            dispose();
    }//GEN-LAST:event_btnlistaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaAbertura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaAbertura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaAbertura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaAbertura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaAbertura().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ABERTURA;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnadiciona;
    private javax.swing.JButton btnlista;
    // End of variables declaration//GEN-END:variables
}
